### ISSUE TITLE
Toggle to disable or enable a button (component)

### ISSUE THREAD

**Issue by Distractic** [Kotlin-Discord/kord-extensions#120]
# Summary

Add a way to disable and enable a button in a component.
So when the button is disabled, it can be enabled and vice versa.

# Current Behaviour

There is no easy way to do this.

# Preferred Behaviour

Maybe in the component, add a method to enable or not a button for an index

**Comment by gdude2002** [comment]
This should be addressed in the most recent commit.

Due to a lack of some API structures in Kord, it's impossible to make this usefully automatic. That said, you can keep track of your `ComponentContainer` object and the button objects you may wish to modify, call `disable()` or `enable()` against the button objects, and apply the same container to a message builder.
