### ISSUE TITLE
Paginator: Add event to new reaction

### ISSUE THREAD

**Issue by Distractic** [Kotlin-Discord/kord-extensions#16]
## Explication

During the creation of a _Paginator_, it is not possible to simply add a reaction with an event.
A feature to solve this problem is a method similar to : 

```kotlin
myPaginator.addReaction(ReactionEmoji.Unicode("\uD83C\uDFD3")) { //PaginatorReactionEvent
 //execution
}
```
And the event has a signature similar to : 
```kotlin
data class PaginatorEvent(val paginator: Paginator, val author: User, val message: Message, val reaction: ReactionEmoji, val isAdded: Boolean)
```

## Suggestion

In _Paginator_, it is necessary to replace : 
```kotlin
public open val reactions: MutableList<ReactionEmoji> = mutableListOf<ReactionEmoji>()
```
by
```kotlin
public open val reactions: MutableMap<ReactionEmoji, suspend (PaginatorReactionEvent) -> Unit> = mutableMapOf()
```
and all events with each emoji will placed in this map

**Comment by gdude2002** [comment]
I'm not 100% sure how well this would fit into the workflow of a paginator at the moment. I feel like this might be more sensible as a more generic interface - like, for example, live messages - which you can listen for events for already. Furthermore, I'm not sure adding this functionality to the _current_ paginator makes sense. This seems like an entirely separate concept, some kind of... reactable embeds? I'm not sure.

This idea should be fleshed out into a less-niche use case, in my opinion. For the time being, I don't think it belongs in mainline - this should be a custom paginator subclass. That's why it's an `open class`, after all!
