### ISSUE TITLE
Duplicate class kotlin.internal.OnlyInputTypes found in modules kord-extensions-1.6.0 (com.kotlindiscord.kord.extensions:kord-extensions:1.6.0) and kotlin-stdlib-2.0.0 (org.jetbrains.kotlin:kotlin-stdlib:2.0.0)

### ISSUE THREAD

**Issue by Xinerfapre** [Kotlin-Discord/kord-extensions#303]
Hi,

In an Android project, if we add the kord-extensions dependency and want to build an apk, the "checkDebugDuplicateClasses" task finds the duplicated class `kotlin.internal.OnlyInputTypes` :

> \> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
>    \> Duplicate class kotlin.internal.OnlyInputTypes found in modules kord-extensions-1.6.0.jar -> kord-extensions-1.6.0 (com.kotlindiscord.kord.extensions:kord-extensions:1.6.0) and kotlin-stdlib-2.0.0.jar -> kotlin-stdlib-2.0.0 (org.jetbrains.kotlin:kotlin-stdlib:2.0.0)

After looking at the project, I found [the duplicated class](https://github.com/Kord-Extensions/kord-extensions/blob/root/kord-extensions/src/main/kotlin/kotlin/internal/Annotations.kt#L16) which is also in the [org.jetbrains.kotlin:kotlin-stdlib package](https://github.com/JetBrains/kotlin/blob/ede0373c4e5c0506b1491c6eb4c8bc0660ef7d21/libraries/stdlib/src/kotlin/internal/Annotations.kt#L42) which is implemented in [these sub-projects](https://github.com/search?q=repo%3AKord-Extensions%2Fkord-extensions%20kotlin.stdlib&type=code).

Is this normal?
Isn't there an alternative to that?

**Comment by gdude2002** [comment]
Hey there, thanks for the question!

Yes, this is intentional. This annotation is a Kotlin internal annotation that we make use of in the `ChangeSet` type, and because it's marked `internal`, we have to provide our own version of it with the same package for us to be able to use it and have it behave as expected.

[This YouTrack issue](https://youtrack.jetbrains.com/issue/KT-13198) was submitted about 8 years ago. About 7 years ago, [a JetBrains team member stated that they intended to make this annotation public](https://discuss.kotlinlang.org/t/restrict-type-by-receiver/5492/2), but, well, this still hasn't happened.

I'm open to alternatives, but the only other approach I'm aware of is a suppression hack from 2021. Have y'all got any ideas?

**Comment by DRSchlaubi** [comment]
You could just use `@Supress("INVISIBLE_REFERENCE")` instead of duplicating the class

**Comment by gdude2002** [comment]
That's the suppression hack I talked about - `@Suppress("INVISIBLE_MEMBER", "INVISIBLE_REFERENCE")`

It makes the code hella messy, but at least it seems to work - I'll push after testing.

**Comment by gdude2002** [comment]
I've pushed this ugly-ass code to `1.8.1-SNAPSHOT`, and it should be available in 15 minutes or so.

```kt
public operator fun <
	@Suppress("INVISIBLE_MEMBER", "INVISIBLE_REFERENCE")
	@kotlin.internal.OnlyInputTypes
	T : Any?,
	> set(

	key: KProperty<T>,
	value: Change<T>,
) {
	changes[key] = value
}
```

I sure wish there was a better way, haha

**Comment by DRSchlaubi** [comment]
I usually use file: annotations
