### ISSUE TITLE
Unload extensions on disconnect event

### ISSUE THREAD

**Issue by bosukas** [Kotlin-Discord/kord-extensions#48]
# Summary

Currently there is nothing in the life cycle that uses the unload method in the extension classes. This is a problem as extensions that use the unload method will never be unloaded. This could cause an inconvenience if the unload method saves data, etc (unless the user handles it themselves).

# Suggestions

Maybe an idea would be to have a defaulting behaviour of extensions being unloaded when the bot receives a disconnect / shutdown event, which can be turned off if users wish to manage unloading extensions themselves.

**Comment by gdude2002** [comment]
I definitely don't want to unload extensions when the gateway is disconnected - there are tons of reasons why that could happen, but Kord and the Discord protocol are designed to handle that gracefully.

A runtime hook might be useful, though.

**Comment by gdude2002** [comment]
Having looked into this, runtime shutdown hooks aren't guaranteed to ever be called - and even if they were, Kord may already have been shut down by that point. Because this is such an unreliable way of cleaning up your extensions and saving data, I'm not going to implement such a hook.

The unload function is intended to be used purely from an extension management perspective - you should build your extensions with the _expectation_ that it'll never be called, but you can use it to kill any coroutines/jobs you've started in the event that the user does have another extension that unloads it.
