### ISSUE TITLE
Issues with message argument type

### ISSUE THREAD

**Issue by Leo40Git** [Kotlin-Discord/kord-extensions#56]
# Description

I have a command that accepts a message as its single argument. However, I've noticed a problem when trying to invoke this command - namely, that the message argument is always invalid (see Media section).

(the only actually invalid argument, AFAICT, is the one where I only gave it the message ID)

# Version

I'm using Kord Extensions `1.4.1-SNAPSHOT`. No other dependencies declared - I'm using the Ktor and Kord versions that Gradle automatically includes with Extensions.

# Code Example
```kt
class TestExtension : Extension() {
    override val name: String = "test"

    override suspend fun setup() {
        command(::DemoArgs) {
            name = "demo"

            action {
                with(arguments) {
                    message.reply {
                        content = "Hello!"
                    }
                }
            }
        }
    }

    class DemoArgs : Arguments() {
        val target by message("target")
    }
}
```

# Media

<details>
  <summary>Click to expand</summary>
  <img src="https://user-images.githubusercontent.com/7997354/123621111-8dce0700-d813-11eb-8770-ef80ae28d57c.png" />
</details>

**Comment by gdude2002** [comment]
This should be fixed in the latest push. Make sure you wait until it's built, and then use this option in IJ (assuming that's what you use)

![image](https://user-images.githubusercontent.com/204153/123775857-a8ad8380-d8c6-11eb-8889-7887e9e2bd57.png)

---

There were two problems here:

1. It seems Kord changed how the `MessageCreateEvent` works, meaning that the channel it contains is always a `MessageChannelBehavior` instead of a subclass, as was previously the case. KordEx will now always resolve the channel object in the `MessageCommandContext`.
2. I had changed how the URL parsing worked, which meant that there were `IndexOutOfBounds` exceptions - I'm not sure why you didn't simply get the generic error message, but I've fixed that as well.

Please reach out to me if anything else is needed!
